"""AUTO-GENERATED by scripts/refresh_instance_rates.py — DO NOT EDIT BY HAND.

Studio-JupyterLab on-demand rates (USD/hour), keyed by REGION then instance type.

Source : AWS Price List API, ServiceCode=AmazonSageMaker,
         platoinstancetype=Studio-JupyterLab
Fetched: 2026-09-24

A type absent from a region's dict is NOT offered for Studio-JupyterLab there, which
is what keeps it out of the participant dropdown. A REGION absent from this file makes
config.py raise at import rather than quote another region's prices — regenerate with:

    ./scripts/refresh_instance_rates.py --region <region> --merge

Prices are NOT quotas. A rate here only means the region sells the type; whether this
account may launch it is a separate per-(account x region) fact. QUOTA_CODES below lets
change_instance resolve that live value with one GetServiceQuota call per request.
"""

RATES_BY_REGION = {
    "ap-northeast-1": {
        # --- CPU ---
        "ml.t3.medium": 0.065,
        "ml.c5.large": 0.128,
        "ml.t3.large": 0.131,
        "ml.m5.large": 0.149,
        "ml.c5.xlarge": 0.257,
        "ml.t3.xlarge": 0.261,
        "ml.m5.xlarge": 0.298,
        "ml.c5.2xlarge": 0.514,
        "ml.t3.2xlarge": 0.522,
        "ml.m5.2xlarge": 0.595,
        "ml.m5.4xlarge": 1.19,
        # --- GPU ---
        "ml.g4dn.xlarge": 0.994,
        "ml.g4dn.2xlarge": 1.269,
        "ml.g6.xlarge": 1.6341,
        "ml.g6.2xlarge": 1.7723,
        "ml.g5.xlarge": 2.04,
        "ml.g5.2xlarge": 2.2,
        "ml.g6.4xlarge": 2.3988,
        "ml.g5.4xlarge": 2.94,
        "ml.g5.8xlarge": 4.44,
        "ml.g6.12xlarge": 8.3421,
        "ml.g5.12xlarge": 10.28,
        "ml.g6.24xlarge": 12.1012,
        "ml.g5.24xlarge": 14.76,
        "ml.g6.48xlarge": 24.2026,
        "ml.g5.48xlarge": 29.53,
        "ml.p4d.24xlarge": 34.612516,
        "ml.p5.48xlarge": 79.12,
    },
    "ap-northeast-2": {
        # --- CPU ---
        "ml.t3.medium": 0.062,
        "ml.c5.large": 0.115,
        "ml.t3.large": 0.125,
        "ml.m5.large": 0.142,
        "ml.c5.xlarge": 0.23,
        "ml.t3.xlarge": 0.25,
        "ml.m5.xlarge": 0.283,
        "ml.c5.2xlarge": 0.461,
        "ml.t3.2xlarge": 0.499,
        "ml.m5.2xlarge": 0.566,
        "ml.m5.4xlarge": 1.133,
        # --- GPU ---
        "ml.g4dn.xlarge": 0.906,
        "ml.g4dn.2xlarge": 1.156,
        "ml.g6.xlarge": 1.3854,
        "ml.g6.2xlarge": 1.5026,
        "ml.g5.xlarge": 1.732,
        "ml.g5.2xlarge": 1.863,
        "ml.g6.4xlarge": 2.0338,
        "ml.g5.4xlarge": 2.496,
        "ml.g5.8xlarge": 3.763,
        "ml.g6.12xlarge": 7.0728,
        "ml.g5.12xlarge": 8.718,
        "ml.g6.24xlarge": 10.26,
        "ml.g5.24xlarge": 12.518,
        "ml.g6.48xlarge": 20.52,
        "ml.g5.48xlarge": 25.035,
        "ml.p4d.24xlarge": 34.971822,
    },
    "eu-west-1": {
        # --- CPU ---
        "ml.t3.medium": 0.055,
        "ml.t3.large": 0.109,
        "ml.c5.large": 0.115,
        "ml.m5.large": 0.128,
        "ml.t3.xlarge": 0.219,
        "ml.c5.xlarge": 0.23,
        "ml.m5.xlarge": 0.257,
        "ml.t3.2xlarge": 0.438,
        "ml.c5.2xlarge": 0.461,
        "ml.m5.2xlarge": 0.514,
        "ml.m5.4xlarge": 1.027,
        # --- GPU ---
        "ml.g4dn.xlarge": 0.8218,
        "ml.g4dn.2xlarge": 1.047,
        "ml.g5.xlarge": 1.57,
        "ml.g5.2xlarge": 1.69,
        "ml.g5.4xlarge": 2.27,
        "ml.g5.8xlarge": 3.42,
        "ml.g5.12xlarge": 7.92,
        "ml.g5.24xlarge": 11.36,
        "ml.g5.48xlarge": 22.73,
        "ml.p4d.24xlarge": 27.2730435,
    },
    "us-east-1": {
        # --- CPU ---
        "ml.t3.medium": 0.05,
        "ml.t3.large": 0.1,
        "ml.c5.large": 0.102,
        "ml.m5.large": 0.115,
        "ml.t3.xlarge": 0.2,
        "ml.c5.xlarge": 0.204,
        "ml.m5.xlarge": 0.23,
        "ml.t3.2xlarge": 0.399,
        "ml.c5.2xlarge": 0.408,
        "ml.m5.2xlarge": 0.461,
        "ml.m5.4xlarge": 0.922,
        # --- GPU ---
        "ml.g4dn.xlarge": 0.7364,
        "ml.g4dn.2xlarge": 0.94,
        "ml.g6.xlarge": 1.127,
        "ml.g6.2xlarge": 1.222,
        "ml.g5.xlarge": 1.41,
        "ml.g5.2xlarge": 1.52,
        "ml.g6.4xlarge": 1.654,
        "ml.g5.4xlarge": 2.03,
        "ml.g5.8xlarge": 3.06,
        "ml.g7e.2xlarge": 4.2039,
        "ml.g7e.4xlarge": 4.9977,
        "ml.g6.12xlarge": 5.752,
        "ml.g7e.8xlarge": 6.5853,
        "ml.g5.12xlarge": 7.09,
        "ml.g6.24xlarge": 8.344,
        "ml.g5.24xlarge": 10.18,
        "ml.g7e.12xlarge": 10.3576,
        "ml.g6.48xlarge": 16.688,
        "ml.g5.48xlarge": 20.36,
        "ml.g7e.24xlarge": 20.7152,
        "ml.p4d.24xlarge": 25.2512883,
        "ml.g7e.48xlarge": 41.4304,
        "ml.p5.48xlarge": 63.296,
    },
    "us-west-2": {
        # --- CPU ---
        "ml.t3.medium": 0.05,
        "ml.t3.large": 0.1,
        "ml.c5.large": 0.102,
        "ml.m5.large": 0.115,
        "ml.t3.xlarge": 0.2,
        "ml.c5.xlarge": 0.204,
        "ml.m5.xlarge": 0.23,
        "ml.t3.2xlarge": 0.399,
        "ml.c5.2xlarge": 0.408,
        "ml.m5.2xlarge": 0.461,
        "ml.m5.4xlarge": 0.922,
        # --- GPU ---
        "ml.g4dn.xlarge": 0.7364,
        "ml.g4dn.2xlarge": 0.94,
        "ml.g6.xlarge": 1.127,
        "ml.g6.2xlarge": 1.222,
        "ml.g5.xlarge": 1.41,
        "ml.g5.2xlarge": 1.52,
        "ml.g6.4xlarge": 1.654,
        "ml.g5.4xlarge": 2.03,
        "ml.g5.8xlarge": 3.06,
        "ml.g7e.2xlarge": 4.2039,
        "ml.g7e.4xlarge": 4.9977,
        "ml.g6.12xlarge": 5.752,
        "ml.g7e.8xlarge": 6.5853,
        "ml.g5.12xlarge": 7.09,
        "ml.g6.24xlarge": 8.344,
        "ml.g5.24xlarge": 10.18,
        "ml.g7e.12xlarge": 10.3576,
        "ml.g6.48xlarge": 16.688,
        "ml.g5.48xlarge": 20.36,
        "ml.g7e.24xlarge": 20.7152,
        "ml.p4d.24xlarge": 25.251286,
        "ml.g7e.48xlarge": 41.4304,
        "ml.p5.48xlarge": 63.296,
    },
}


# Studio-JupyterLab service-quota code per instance type, for GetServiceQuota.
#
# NOT keyed by region: codes were measured identical across us-west-2 / ap-northeast-2 /
# eu-west-1 (zero mismatches on every shared type). Which types HAVE a quota does differ
# per region, so a lookup can legitimately miss — callers must treat a miss as 'unknown',
# never as 'quota 0', or they would block a launchable type.
#
# Values are deliberately absent: a quota can be raised minutes after this file is
# generated, so baking one in would make the lab reject a type the account now owns.
QUOTA_CODES = {
    "ml.c5.2xlarge": "L-C1AE5754",
    "ml.c5.large": "L-A6419EF6",
    "ml.c5.xlarge": "L-BD09952F",
    "ml.g4dn.2xlarge": "L-138F29A9",
    "ml.g4dn.xlarge": "L-39F81BFB",
    "ml.g5.12xlarge": "L-8D2ED7BF",
    "ml.g5.24xlarge": "L-F087CCFC",
    "ml.g5.2xlarge": "L-F73C7DB9",
    "ml.g5.48xlarge": "L-83AB5D73",
    "ml.g5.4xlarge": "L-81940D85",
    "ml.g5.8xlarge": "L-19B6BAFC",
    "ml.g5.xlarge": "L-988CE6C5",
    "ml.g6.12xlarge": "L-962247BA",
    "ml.g6.24xlarge": "L-8ACE1754",
    "ml.g6.2xlarge": "L-92D1521D",
    "ml.g6.48xlarge": "L-125B7142",
    "ml.g6.4xlarge": "L-692B8304",
    "ml.g6.xlarge": "L-AABA5942",
    "ml.g7e.12xlarge": "L-5F015F52",
    "ml.g7e.24xlarge": "L-E481E4F8",
    "ml.g7e.2xlarge": "L-7A3E0A2C",
    "ml.g7e.48xlarge": "L-A48244DF",
    "ml.g7e.4xlarge": "L-B7228EBF",
    "ml.g7e.8xlarge": "L-0407753C",
    "ml.m5.2xlarge": "L-7C9662F1",
    "ml.m5.4xlarge": "L-2CA31BFA",
    "ml.m5.large": "L-3BDCD216",
    "ml.m5.xlarge": "L-77B8159A",
    "ml.p4d.24xlarge": "L-AD63F1D2",
    "ml.p5.48xlarge": "L-B41FBF28",
    "ml.t3.2xlarge": "L-B039EA8F",
    "ml.t3.large": "L-2733D4D5",
    "ml.t3.medium": "L-71FAF417",
    "ml.t3.xlarge": "L-61F9C762",
}
